### ISSUE TITLE
Forbedringsforslag

### ISSUE THREAD

**Issue by AndersKlinting** [Thomilist/division-result-bridge#1]
en god ide - og Imponerende kode tiden taget i betragtning.

jeg tænkte at istedet for at konfigurere både meos og divi-detaljer (meos url, divi exe og divi-fil) og selv initiere beregning, så kunne du jo benytte den indbyggede web-server i divisionsmatch og hente html direkte.  så skal du bare starte en divisionsmatch information server for hver division på hver sin port og konfigurere url til det du vil hente.

det vil også kunne frigøre divison-result-bridge fra at køre på windowsmaskinen med divisionsmatch.

**Comment by Thomilist** [comment]
Tak :)

Det er egentlig en god idé. Jeg er også begyndt at overveje, hvordan jeg kunne undgå at afhænge af MeOS. Ikke at jeg er træt af MeOS, men nogle klubber bruger jo andre programmer hvis de fx har Emit.

Ved at bruge informationsserveren i Divisionsmatchberegning ville jeg så opnå kompatibilitet med alle(?) systemer, der benyttes til divisionsmatch, og der bliver lidt mindre at konfigurere i division-result-bridge. Til gengæld skal man åbne og holde styr på nogle flere vinduer, og man kan selvfølgelig ikke hente konkurrencenavn, arrangør og dato direkte fra MeOS. Ikke nogen dealbreakers dér.

Jeg tænker lidt over det, men umiddelbart tror jeg, at jeg vil tilføje muligheden som et alternativ til den nuværende tilgang.

**Comment by AndersKlinting** [comment]
ja - uafhængighed af MeOS vil gøre det tilgængeligt for et par jyske og fynske klubber og i princippet understøtte alle systemer (jeg tror ikke der er nogen som ikke bruger mit program til beregning).

Refresh/opdatering af resultater sker automatisk, når beregningsprogrammet leverer nye data i en fil, eller på en timer i tilfældet med MeOS Information Server - så du skal jo 'bare' hente nyt HTML på dine egen timer.

Runde, Dato og Skov er informationer, som findes i output fra divisionsmatchen - f.eks i XML output
![image](https://github.com/Thomilist/division-result-bridge/assets/30745841/12a81856-99a7-48e1-ba75-0c783aa03cab)
Arrangør findes ikke - men alle disse detaljer kunne være noget man skulle indtastes i hånden i stedet for at bruge MeOS.

Alternativt kunne Carsten Stenberg og jeg jo overveje at addere f.eks arrangør til xml-formatet, som udveksles.

**Comment by Thomilist** [comment]
Det er sådan set relativt simpelt, ja, og det ville ikke kræver den store omvæltning i koden. Jeg giver det et skud.

Med hensyn til metadata, så er der også felter til manuel indtastning. Indhentning fra MeOS blev tilføjet som en bekvemmelighedsfunktion, når nu man alligevel kobler på informationsserveren. Det giver også lidt mindre risiko for tastefejl, når man ikke skal skrive det samme flere gange, men det er ikke super kritisk.

Jeg kunne dog godt forestille mig, at det kunne være brugbart med lidt mere metadata fra Divisionsmatchberegning, måske noget i retning af MeOS' `/meos?get=competition` og `/meos?get=status`? Så kunne man programmatisk kontrollere, at man har fat i det rigtige program, den rigtige version og den rigtige konkurrence.

**Comment by Thomilist** [comment]
Det er blevet tilføjet nu i [#6d8401d](https://github.com/Thomilist/division-result-bridge/commit/6d8401d98e712a546e898f33ec95c454d23eac03). Kernen af funktionaliteten i [src/workers/DivisionInterface](https://github.com/Thomilist/division-result-bridge/blob/main/src/workers/DivisionInterface.cpp) var ganske ligetil, men det blev alligevel til den store omvæltning i koden, primært for at tilpasse interfacet og guide brugeren lidt bedre. 

Ikke så overraskende er det også markant hurtigere at hente resultaterne fra informationsserveren end at skulle starte en proces, som skriver en fil, og så indlæse filen bagefter - nærmest øjeblikkeligt vs. et par sekunder. Dog savner jeg lidt en måde at læse, om der er sket ændringer siden sidste API call.

Men hey, jeg synes det er en stor forbedring i forhold til før. Tak for godt input :)

**Comment by Thomilist** [comment]
Inkluderet i [seneste release](https://github.com/Thomilist/division-result-bridge/releases/tag/1.1.0).
